version: '3'
services:
  notifier-mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - notifier-mongodb-storage:/data/db
    ports:
      - 27017:27017
  notifier:
    image: francescorivola/tribeca-notifier:latest
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://notifier-mongodb:27017
      - DATABASE_NAME=tribeca_notifier
      - HTTP_PORT=30701
    ports:
      - "30701:30701"
volumes:
  notifier-mongodb-storage: