version: '3'
services:
  cep-mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - cep-mongodb-storage:/data/db
    ports:
      - 27017:27017
  cep:
    image: francescorivola/tribeca-cep:latest
    environment:
      - CEP_MONGODB_URL=mongodb://cep-mongodb:27017
      - CEP_ADMIN_HTTP_HOST=0.0.0.0
      - CEP_ADMIN_HTTP_PORT=8888
      - CEP_EVENT_PROCESSING_HTTP_HOST=0.0.0.0
      - CEP_EVENT_PROCESSING_HTTP_PORT=8889
    ports:
      - "8888:8888"
      - "8889:8889"
  cep-ui:
    image: francescorivola/tribeca-cep-ui:latest
    environment:
      - BASE_URL=http://localhost:8888
    ports:
      - "8890:80"
volumes:
  cep-mongodb-storage: