version: '3'
services:
  mapper-mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mapper-mongodb-storage:/data/db
    ports:
      - 27017:27017
  mapper:
    image: francescorivola/tribeca-mapper:latest
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://mapper-mongodb:27017
      - DATABASE_NAME=tribeca_mapper
      - HTTP_PORT=30702
    ports:
      - "30702:30702"
volumes:
  mapper-mongodb-storage: